### ISSUE TITLE
Resurrecting dead people

### ISSUE THREAD

**Issue by gabeins** [Shpigford/covid-containment#2]
I somehow managed to get negative `deaths` and `infected` numbers. 

<img width="721" alt="Screenshot 2020-03-26 at 11 44 06" src="https://user-images.githubusercontent.com/192261/77638508-91f7de80-6f57-11ea-9d77-033e6a5c3421.png">

The "treat infected" button was going on automatically for some time, so I guess there's an issue with the handler?

**Comment by Shpigford** [comment]
I guess the opposite of dying is _birthing_? 🙃

Do you happen to recall how many doctors you had hired?

**Comment by gabeins** [comment]
I have 17 doctors hired at the moment. When the issue first started I was actively hiring more as fast as I could

**Comment by gabeins** [comment]
![Kapture 2020-03-29 at 18 24 58](https://user-images.githubusercontent.com/192261/77854455-cd5e0b80-71ea-11ea-8473-3718db5b5f28.gif)
